APP_NAME: db-exporter

image: prom/mysqld-exporter

targetHosts:
  - name: db-exporter-default
    secretName: db-secret
    secretKeyDbUser: DB_USERNAME
    secretKeyDbPassword: DB_PASSWORD
    host: host.example.com:3306
